### ISSUE TITLE
URL not Working Properly after sign up button

### ISSUE THREAD

**Issue by shudiptod** [shudiptod/twitterclone#2]
#1 
```
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account Created for {username}.')
            return redirect('login/')
    else:
        form = UserRegisterForm()

    return render (request,'user/register.html', {'form':form})
```

**Comment by shudiptod** [comment]
`def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account Created for {username}.')
            return redirect('login')
    else:
        form = UserRegisterForm()

    return render (request,'user/register.html', {'form':form})`


#removed the **'/'** from **return redirect('login/')**

**Comment by rejoanafridi** [comment]
is this solved???

**Comment by shudiptod** [comment]
> is this solved???

solved

**Comment by shudiptod** [comment]
good job and thank you
